name: Commit Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v6
    permissions:
      contents: read
      pull-requests: read